<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    
    <title>Welcome to Nano Framework</title>
    <meta name="description" content="">
    <meta name="author" content="">
    
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>static/css/style.css" type="text/css" media="screen" />
</head>
<body>
	
    <div id="content">
        
        <h1>Welcome to Nano Framework</h1>
        <p>To get started please read the documentation at <a href="https://github.com/ncou/NanoMVC">https://github.com/ncou/NanoMVC</a>.</p>
        
    </div>

</body>
</html>